language: node_js
node_js:
- '8'
notifications:
  slack:
    secure: wJcdrSBSeco4F1jWuWX4OVeaTRyEeS+1ZE5kDWXGeQpBtB9aI9b6Heq+g72LSkEedY4H3ypNuzUM1cKn0fMeJ1zOhAQLw7VH7GybF0h33JSSxUD9XaKsikDjD9Y9JFWaH+C3GK99402dlf+IFFt8UFzebT1m0JgESLju4y+Tepqva+2a7P9cvPs0l42Vo1eX3Xrb6Eh29/ZD62GJBJMHs/iLYCwdCp3ddwclNJUTmuR+pU74Cii3F3j2CdEnYcjynm+m2BZZJ0h9vMtwMfNdCGCi5xxZDHo0QncpA8NdKvA6+PjPfTnSZLo1GgKj3FP7lAxkQm4h9XcE1Eikvu/XGZ2L8MvsqGjwH41RbJYJY93t+FU2e8G5HzC/LS3eqU/QoFmAUwRnVZdIXkf+zl5xl5sQpwL4HH6k/oMF5nKhJMOgYH3GIGPoX76djAMf+E9rtLEwAjsM+/gsZv1rN2bTozz2foL8VlEZ12zCbVXcVkkG4H2NFrGz05wF/2XGVnkvmLgIeb4vVy9NEDvD6uXeiCSjjhM/LeyAurcsLw4s5pWeLGeSr9eQussYfz7y8glBu324t/LgQYobS+StQU93doUPzUfn8qmM4rBmAKxMD0GB0sv62tzEsMcVVcIjij2KL+FTVMd8zn1i6veD1zfY0Lr5KnxPbQM52pJXeL/aTPo=
